# Generated by Django 4.2.11 on 2024-05-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_size_remove_product_quantity_productsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='id_size',
            new_name='size',
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
    ]
