# Generated by Django 5.0.6 on 2024-05-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_category_rename_account_id_detail_account_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products'),
        ),
    ]
